apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: carta-controller-role
  namespace: carta
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: carta-controller-sa
  namespace: carta
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: carta-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carta-controller-role
subjects:
- kind: ServiceAccount
  name: carta-controller-sa
  namespace: carta
