apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carta-cephfs-pvc
  namespace: carta
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 1Gi
