apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-images-pvc 
  namespace: carta
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
