# carta-backend-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: carta-backend
  namespace: carta
spec:
  type: NodePort
  selector:
    app: carta-backend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
