# 1) Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: carta
---
# 2) CephFS PVC (RWX)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carta-data
  namespace: carta
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
---
# 3) Deployment (PVC mounted at /images)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carta-backend
  namespace: carta
  labels:
    app: carta-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: carta-backend
  template:
    metadata:
      labels:
        app: carta-backend
    spec:
      # Ensure CephFS files are owned/accessible by cartauser (1000)
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      # Fix ownership/permissions on /images before the app starts
      containers:
        - name: carta-backend
          image: cartavis/carta:beta
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3002
          volumeMounts:
            - name: carta-storage
              mountPath: /images          # CARTA scans this by default
          startupProbe:
            tcpSocket: { port: 3002 }
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            tcpSocket: { port: 3002 }
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket: { port: 3002 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: carta-storage
          persistentVolumeClaim:
            claimName: carta-data
---
# 4) NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: carta-backend
  namespace: carta
spec:
  type: NodePort
  selector:
    app: carta-backend
  ports:
    - name: tcp
      port: 3002
      targetPort: 3002
      # nodePort: 32002

