# 1) Namespace
#
apiVersion: v1
kind: Namespace
metadata:
  name: carta
---
# 2) (CephFS) PersistentVolumeClaim in carta
# - Uses StorageClass "rook-cephfs"
# - RWX so multiple pods could mount if you scale later
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carta-data
  namespace: carta
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: rook-cephfs
  resources:
    cartavis/carta:betarequests:
      storage: 20Gi
  volumeMode: Filesystem
---
# 3) Deployment (mounts the PVC instead of hostPath)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carta-backend
  namespace: carta
  labels:
    app: carta-backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate              # safe for single-writer paths; fine to keep with RWX
  selector:
    matchLabels:
      app: carta-backend
  template:
    metadata:
      labels:
        app: carta-backend
    spec:
      containers:
        - name: carta-backend
          image: 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3002
          volumeMounts:
            - name: carta-storage
              mountPath: /images   # better than /root; change if your app expects a different path
          startupProbe:
            tcpSocket: { port: 3002 }
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            tcpSocket: { port: 3002 }
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket: { port: 3002 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: carta-storage
          persistentVolumeClaim:
            claimName: carta-data
---
# 4) NodePort Service (external access)
apiVersion: v1
kind: Service
metadata:
  name: carta-backend
  namespace: carta
spec:
  type: NodePort
  selector:
    app: carta-backend
  ports:
    - name: tcp
      port: 3002
     # targetPort: 3002
      #nodePort: 32002  # optional: pin a port; remove this line to let K8s choose
      

