# carta-backend.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: carta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carta-backend
  namespace: carta
  labels:
    app: carta-backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: carta-backend
  template:
    metadata:
      labels:
        app: carta-backend
    spec:
      containers:
        - name: carta-backend
          image: cartavis/carta:beta
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3002
          livenessProbe:
            httpGet:
              path: /config
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: carta-backend
  namespace: carta
  labels:
    app: carta-backend
spec:
  type: ClusterIP
  selector:
    app: carta-backend
  ports:
    - name: http
      port: 3002
      targetPort: 3002
